Repository rdkcentral/Ripple, pull requests merged in 2023-10, with the labels that each got.

#257 fix: Discovery.contentAccess API date-time format is forced to one particular format
  core/sdk/src/utils/serde_utils.rs
Labels: ready-for-qa

#237 feat: Voice Guidance speed change does not trigger onVoiceGuidanceSettingsChanged event
  core/main/src/firebolt/handlers/voice_guidance_rpc.rs
  core/main/src/processor/settings_processor.rs
  core/main/src/processor/storage/default_storage_properties.rs
  core/sdk/src/api/device/device_accessibility_data.rs
  core/sdk/src/api/device/device_events.rs
  core/sdk/src/api/device/device_request.rs
  core/sdk/src/api/storage_property.rs
  core/sdk/src/extn/extn_client_message.rs
  device/thunder_ripple_sdk/src/bootstrap/setup_thunder_pool_step.rs
  device/thunder_ripple_sdk/src/events/thunder_event_processor.rs
  device/thunder_ripple_sdk/src/processors/events/thunder_event_handlers.rs
  device/thunder_ripple_sdk/src/processors/thunder_device_info.rs
  device/thunder_ripple_sdk/src/processors/thunder_events.rs
Labels: enhancement, ready-for-qa

#251 location removed.
  examples/manifest/device-manifest-example.json
Labels: ready-for-qa, OSS-only

#232 feat: Do not show user grant if calling app is not in active state
  core/main/src/firebolt/handlers/privacy_rpc.rs
  core/main/src/service/apps/app_events.rs
  core/main/src/service/apps/delegated_launcher_handler.rs
  core/main/src/service/data_governance.rs
  core/main/src/service/extn/ripple_client.rs
  core/main/src/service/user_grants.rs
  core/main/src/state/platform_state.rs
  core/sdk/src/api/firebolt/fb_capabilities.rs
  core/sdk/src/api/gateway/rpc_gateway_api.rs
  core/sdk/src/extn/client/extn_client.rs
  device/thunder_ripple_sdk/src/client/thunder_client_pool.rs
  device/thunder_ripple_sdk/src/processors/thunder_browser.rs
  device/thunder_ripple_sdk/src/processors/thunder_device_info.rs
  device/thunder_ripple_sdk/src/processors/thunder_persistent_store.rs
Labels: enhancement, ready-for-qa

#246 Usergrant fixes
  core/launcher/src/manager/app_launcher.rs
  core/main/src/firebolt/handlers/profile_rpc.rs
  core/main/src/firebolt/handlers/user_grants_rpc.rs
  core/main/src/service/apps/delegated_launcher_handler.rs
  core/main/src/service/apps/provider_broker.rs
  core/main/src/service/user_grants.rs
  core/sdk/src/api/firebolt/fb_lifecycle_management.rs
  core/sdk/src/api/firebolt/fb_pin.rs
  core/sdk/src/api/firebolt/provider.rs
  core/sdk/src/framework/file_store.rs
  device/thunder_ripple_sdk/src/processors/events/thunder_event_handlers.rs
Labels: ready-for-qa

#261 Permission aliases
  core/main/src/state/cap/permitted_state.rs
  core/sdk/src/api/manifest/device_manifest.rs
Labels: ready-for-qa

#245 Fixed session behavior when an app is launched again while still unloading
  core/main/src/service/apps/delegated_launcher_handler.rs
Labels: ready-for-qa

#271 fix: Privacy Sync returning not implemented
  core/main/src/firebolt/handlers/privacy_rpc.rs
Labels: ready-for-qa

#272 fix: Launcher not sending events
  core/launcher/src/manager/app_launcher.rs
  core/launcher/src/manager/container_manager.rs
Labels: ready-for-qa

#259 feat: Do not persist a user grant if the granted return value from provider is null
  core/main/src/firebolt/handlers/profile_rpc.rs
  core/main/src/service/user_grants.rs
  core/sdk/src/api/firebolt/fb_capabilities.rs
  core/sdk/src/api/firebolt/fb_pin.rs
  core/sdk/src/api/firebolt/provider.rs
Labels: ready-for-qa

#277 fix: Serializers for SecureStorage and Language
  core/main/src/firebolt/handlers/secure_storage_rpc.rs
  core/sdk/src/api/device/device_request.rs
  core/sdk/src/api/firebolt/fb_discovery.rs
  core/sdk/src/api/firebolt/fb_secure_storage.rs
  core/sdk/src/utils/serde_utils.rs
Labels: ready-for-qa

#276 feat: implement Advertising.skipRestriction & Advertising.onSkipRestrictionChanged manage APIs
  core/main/src/firebolt/handlers/advertising_rpc.rs
  core/sdk/src/api/storage_property.rs
Labels: ready-for-qa

#253 fix: device serial number in metric events is incorrect
  core/main/src/state/metrics_state.rs
  core/sdk/src/api/device/device_info_request.rs
  device/thunder_ripple_sdk/src/processors/thunder_device_info.rs
Labels: ready-for-qa

#275 fix: adding missing device_timezone_offset field
  core/sdk/src/api/firebolt/fb_metrics.rs
Labels: ready-for-qa

#260 feat: modify user grant
  core/main/src/firebolt/handlers/user_grants_rpc.rs
  core/main/src/processor/store_user_grants_processor.rs
  core/main/src/service/user_grants.rs
  core/sdk/src/api/usergrant_entry.rs
Labels: ready-for-qa

#281 fix: Thunder client (un)subscribe issue
  device/thunder_ripple_sdk/src/client/thunder_client.rs
  device/thunder_ripple_sdk/src/client/thunder_client_pool.rs
Labels: ready-for-qa

#265 Handle businessAnalytics privacy opt out
  core/main/src/bootstrap/extn/start_cloud_sync_step.rs
  core/main/src/firebolt/handlers/privacy_rpc.rs
  core/main/src/processor/metrics_processor.rs
  core/main/src/processor/storage/default_storage_properties.rs
  core/main/src/service/data_governance.rs
  core/sdk/src/api/distributor/distributor_privacy.rs
  core/sdk/src/api/firebolt/fb_metrics.rs
  core/sdk/src/api/manifest/device_manifest.rs
  core/sdk/src/api/storage_property.rs
  distributor/general/src/general_privacy_processor.rs
Labels: ready-for-qa

#258 Ripple context Version 1.0
  core/launcher/src/manager/app_launcher.rs
  core/main/src/bootstrap/boot.rs
  core/main/src/bootstrap/extn/load_session_step.rs
  core/main/src/bootstrap/extn/mod.rs
  core/main/src/bootstrap/extn/start_cloud_sync_step.rs
  core/main/src/firebolt/handlers/device_rpc.rs
  core/main/src/firebolt/handlers/voice_guidance_rpc.rs
  core/main/src/firebolt/rpc_router.rs
  core/main/src/processor/main_context_processor.rs
  core/main/src/processor/mod.rs
  core/main/src/service/context_manager.rs
  core/main/src/service/mod.rs
  core/main/src/service/user_grants.rs
  core/main/src/state/metrics_state.rs
  core/main/src/state/platform_state.rs
  core/sdk/src/api/context.rs
  core/sdk/src/api/device/device_events.rs
  core/sdk/src/api/device/device_info_request.rs
  core/sdk/src/api/device/device_request.rs
  core/sdk/src/api/firebolt/fb_authentication.rs
  core/sdk/src/api/mod.rs
  core/sdk/src/api/session.rs
  core/sdk/src/api/storage_property.rs
  core/sdk/src/extn/client/extn_client.rs
  core/sdk/src/extn/extn_client_message.rs
  core/sdk/src/framework/ripple_contract.rs
  device/thunder/src/thunder_ffi.rs
  device/thunder_ripple_sdk/src/client/thunder_client.rs
  device/thunder_ripple_sdk/src/events/thunder_event_processor.rs
  device/thunder_ripple_sdk/src/processors/events/thunder_event_handlers.rs
  device/thunder_ripple_sdk/src/processors/thunder_device_info.rs
  device/thunder_ripple_sdk/src/processors/thunder_events.rs
  device/thunder_ripple_sdk/src/tests/contracts/thunder_device_info_pacts.rs
  distributor/general/src/general_session_processor.rs
  examples/manifest/extn-manifest-example.json
  examples/manifest/extn-manifest-tm-example.json
  examples/manifest/jsonrpsee-manifest-example.json
  ripple
Labels: ready-for-qa

#244 Support leaving ClosedCaption styles up to the app
  core/main/src/firebolt/handlers/closed_captions_rpc.rs
  core/main/src/processor/settings_processor.rs
  core/main/src/processor/storage/default_storage_properties.rs
  core/main/src/processor/storage/storage_manager.rs
  core/sdk/src/api/device/device_accessibility_data.rs
  core/sdk/src/api/device/device_peristence.rs
  core/sdk/src/api/manifest/device_manifest.rs
  core/sdk/src/api/storage_property.rs
  device/thunder_ripple_sdk/src/processors/thunder_persistent_store.rs
Labels: ready-for-qa

#268 Share watch history basedon usergrants
  core/main/src/firebolt/firebolt_gatekeeper.rs
  core/main/src/firebolt/handlers/capabilities_rpc.rs
  core/main/src/firebolt/handlers/discovery_rpc.rs
  core/main/src/processor/storage/storage_manager.rs
  core/main/src/service/user_grants.rs
  core/sdk/src/api/storage_property.rs
Labels: ready-for-qa

#280 feat: clear out user grants that are delete from cloud service
  core/main/src/processor/store_user_grants_processor.rs
  core/main/src/service/user_grants.rs
  core/sdk/src/api/device/device_user_grants_data.rs
  core/sdk/src/api/usergrant_entry.rs
Labels: ready-for-qa

#291 fix: should not store grant when app state is unavailable
  core/main/src/service/user_grants.rs
Labels: ready-for-qa

#266 Usergrant request cap req cap info
  core/main/src/firebolt/handlers/capabilities_rpc.rs
  core/main/src/firebolt/handlers/user_grants_rpc.rs
  core/main/src/service/apps/delegated_launcher_handler.rs
  core/main/src/service/extn/ripple_client.rs
  core/main/src/service/user_grants.rs
  core/main/src/state/cap/permitted_state.rs
  core/sdk/src/api/device/device_user_grants_data.rs
  core/sdk/src/api/firebolt/fb_capabilities.rs
  core/sdk/src/api/firebolt/fb_user_grants.rs
Labels: ready-for-qa

#285 feat: Discovery lifecycle issues
  core/launcher/src/launcher_lifecycle_processor.rs
  core/launcher/src/manager/app_launcher.rs
  core/main/src/service/apps/delegated_launcher_handler.rs
  core/sdk/src/api/apps.rs
  core/sdk/src/api/device/entertainment_data.rs
  core/sdk/src/api/firebolt/fb_discovery.rs
  core/sdk/src/api/firebolt/fb_lifecycle_management.rs
Labels: ready-for-qa

#288 fix: capabilities info for app ignore
  core/main/src/firebolt/handlers/advertising_rpc.rs
  core/main/src/firebolt/handlers/capabilities_rpc.rs
  core/main/src/firebolt/handlers/privacy_rpc.rs
  core/main/src/processor/settings_processor.rs
  core/main/src/state/cap/cap_state.rs
  core/main/src/state/cap/permitted_state.rs
  core/main/src/utils/test_utils.rs
  core/sdk/src/api/firebolt/fb_capabilities.rs
  core/sdk/src/api/firebolt/fb_openrpc.rs
Labels: ready-for-qa

#292 fix: ripple sends wrong eventName
  core/sdk/src/api/firebolt/fb_capabilities.rs
Labels: ready-for-qa

#284 feat: Api support for preferredlang and audio desc
  core/main/src/bootstrap/start_fbgateway_step.rs
  core/main/src/firebolt/handlers/audio_description_rpc.rs
  core/main/src/firebolt/handlers/closed_captions_rpc.rs
  core/main/src/firebolt/handlers/discovery_rpc.rs
  core/main/src/firebolt/handlers/localization_rpc.rs
  core/main/src/firebolt/mod.rs
  core/main/src/processor/storage/storage_manager.rs
  core/main/src/processor/storage/storage_manager_utils.rs
  core/main/src/state/firebolt-open-rpc.json
  core/sdk/src/api/device/device_accessibility_data.rs
  core/sdk/src/api/device/entertainment_data.rs
  core/sdk/src/api/firebolt/fb_localization.rs
  core/sdk/src/api/mod.rs
  core/sdk/src/api/storage_property.rs
  examples/manifest/device-manifest-example.json
Labels: ready-for-qa
