Repository rdkcentral/Ripple, pull requests merged in 2023-09, with the labels that each got.

#209 178 launcher extension needs to pass on session
  core/launcher/Cargo.toml
  core/launcher/src/launcher_state.rs
  core/launcher/src/manager/app_launcher.rs
  core/sdk/src/api/manifest/apps.rs
Labels: accelerator-ui

#231 feat: Support for providing Platform token
  core/main/src/firebolt/handlers/authentication_rpc.rs
  core/main/src/state/platform_state.rs
  core/sdk/src/api/distributor/distributor_platform.rs
  core/sdk/src/api/mod.rs
  core/sdk/src/extn/extn_client_message.rs
Labels: enhancement, ready-for-qa

#240 feat: Port secureStorage manage APIs
  core/main/src/firebolt/handlers/secure_storage_rpc.rs
  core/sdk/src/api/firebolt/fb_secure_storage.rs
  distributor/general/src/general_securestorage_processor.rs
Labels: enhancement, ready-for-qa

#226 Commit privacy settings to local on success from ESS
  core/main/src/firebolt/handlers/privacy_rpc.rs
  core/main/src/processor/storage/storage_manager.rs
Labels: enhancement, ready-for-qa

#252 fix: Authentication always return Platform
  core/main/src/firebolt/handlers/authentication_rpc.rs
  core/main/src/state/platform_state.rs
  device/thunder_ripple_sdk/src/tests/contracts/contract_utils.rs
Labels: ready-for-qa

#242 feat: Ripple should override the source field in the intent for Discovery.launch
  core/main/src/firebolt/handlers/discovery_rpc.rs
  core/main/src/firebolt/handlers/lcm_rpc.rs
  core/sdk/src/api/device/entertainment_data.rs
  core/sdk/src/api/manifest/device_manifest.rs
Labels: enhancement, ready-for-qa
