Repository rdkcentral/Ripple, pull requests merged in 2023-11, with the labels that each got.

#289 fix: Fixed issues with SessionTransitionCanceled event notification
  core/main/src/service/apps/delegated_launcher_handler.rs
  core/main/src/service/user_grants.rs
Labels: ready-for-qa

#286 feat: Add LifecycleManagement related BI metrics & Telemetry
  core/main/src/processor/metrics_processor.rs
  core/main/src/service/apps/delegated_launcher_handler.rs
  core/main/src/service/extn/ripple_client.rs
  core/main/src/service/telemetry_builder.rs
  core/sdk/src/api/firebolt/fb_metrics.rs
  core/sdk/src/api/firebolt/fb_telemetry.rs
  device/thunder_ripple_sdk/src/processors/thunder_telemetry.rs
  distributor/general/src/general_metrics_processor.rs
  examples/manifest/extn-manifest-example.json
  examples/manifest/extn-manifest-tm-example.json
  examples/manifest/jsonrpsee-manifest-example.json
Labels: ready-for-qa

#287 update manifests for supporting accelerator UI
  core/launcher/src/manager/container_manager.rs
  core/launcher/src/manager/view_manager.rs
  core/main/src/firebolt/handlers/localization_rpc.rs
  distributor/general/src/general_metrics_processor.rs
  distributor/general/src/general_securestorage_processor.rs
  distributor/general/src/general_session_processor.rs
  examples/reference-manifest/IpStb/firebolt-app-library.json
  examples/reference-manifest/IpStb/firebolt-device-manifest.json
  examples/reference-manifest/IpStb/firebolt-extn-manifest.json
Labels: accelerator-ui

#270 Fix/ad policy events
  core/main/src/firebolt/handlers/advertising_rpc.rs
  core/main/src/service/apps/app_events.rs
  core/sdk/src/api/firebolt/fb_capabilities.rs
  core/sdk/src/api/storage_property.rs
  core/sdk/src/utils/error.rs
  device/thunder_ripple_sdk/src/client/thunder_client.rs
Labels: bug, good first issue, ready-for-qa

#293 Support non-negotiable public firebolt apis
  core/main/src/firebolt/firebolt_gatekeeper.rs
  core/main/src/state/cap/generic_cap_state.rs
Labels: ready-for-qa

#299 feat: handle missing provider case for evaluateAt=activeSession
  core/main/src/service/apps/delegated_launcher_handler.rs
  core/main/src/service/user_grants.rs
  core/main/src/state/cap/generic_cap_state.rs
Labels: ready-for-qa

#312 fix: Fixed Limit Ad Tracking values
  core/main/src/firebolt/handlers/privacy_rpc.rs
Labels: ready-for-qa

#274 fix: Appsanity Permissions are directly being mapped to data-usage capability
  core/main/src/state/cap/permitted_state.rs
Labels: ready-for-qa

#309 feat: Send initial intent when app calls Lifecycle.ready
  core/main/src/service/apps/delegated_launcher_handler.rs
  core/sdk/src/api/manifest/device_manifest.rs
Labels: ready-for-qa

#300 Lifespan once fix
  core/main/src/firebolt/handlers/user_grants_rpc.rs
  core/main/src/service/user_grants.rs
Labels: ready-for-qa

#294 feat: optimization changes
  core/main/src/firebolt/handlers/localization_rpc.rs
  core/main/src/service/context_manager.rs
  core/sdk/src/api/context.rs
  core/sdk/src/api/device/device_events.rs
  core/sdk/src/api/device/device_info_request.rs
  core/sdk/src/api/device/device_request.rs
  core/sdk/src/api/session.rs
  core/sdk/src/extn/client/extn_client.rs
  core/sdk/src/extn/extn_client_message.rs
  device/thunder_ripple_sdk/src/events/thunder_event_processor.rs
  device/thunder_ripple_sdk/src/processors/events/thunder_event_handlers.rs
  device/thunder_ripple_sdk/src/processors/thunder_device_info.rs
  device/thunder_ripple_sdk/src/processors/thunder_events.rs
  examples/manifest/extn-manifest-example.json
  examples/manifest/extn-manifest-tm-example.json
  examples/manifest/jsonrpsee-manifest-example.json
Labels: ready-for-qa

#306 feat: UserGrants exclusion filter support added
  core/main/src/firebolt/firebolt_gatekeeper.rs
  core/main/src/firebolt/handlers/capabilities_rpc.rs
  core/main/src/firebolt/handlers/user_grants_rpc.rs
  core/main/src/service/apps/delegated_launcher_handler.rs
  core/main/src/service/user_grants.rs
  core/sdk/src/api/device/device_user_grants_data.rs
  core/sdk/src/api/manifest/device_manifest.rs
Labels: ready-for-qa

#321 fix: Advertising.onPolicyChanged event not generated when changing allowAppContentAdTargeting
  core/main/src/processor/storage/storage_manager.rs
  core/sdk/src/api/storage_property.rs
Labels: ready-for-qa

#304 fix: Fix for capabilities.granted parameter validation
  core/main/src/firebolt/firebolt_ws.rs
  core/main/src/firebolt/handlers/capabilities_rpc.rs
  core/main/src/state/session_state.rs
  distributor/general/src/general_permission_processor.rs
  distributor/general/src/general_permissions_map.json
Labels: ready-for-qa

#318 fix: capabilities.granted is not returnng grant denied response
  core/main/src/firebolt/handlers/capabilities_rpc.rs
Labels: ready-for-qa

#303 Remove unused ad storage property
  core/sdk/src/api/storage_property.rs
Labels: ready-for-qa

#317 fix: uncomnent closed caption params, messed up during the merge
  core/main/src/processor/storage/default_storage_properties.rs
Labels: ready-for-qa

#336 fix: Fixed error message & code to: not supported & -50100
  core/main/src/firebolt/handlers/authentication_rpc.rs
Labels: ready-for-qa

#332 fix: settings throwing custom error
  core/main/src/service/user_grants.rs
Labels: ready-for-qa
