Repository rdkcentral/Ripple, pull requests merged in 2023-08, with the labels that each got.

#187 Improve setup process
  README.md
  ripple
Labels: documentation, enhancement

#191 fix: Move the Extension starter to a new thread
  core/main/src/state/extn_state.rs
Labels: bug, Resiliency

#195 feat: Adding features for SystemD and RPC
  Cargo.toml
  core/launcher/Cargo.toml
  core/main/Cargo.toml
  core/main/src/bootstrap/start_fbgateway_step.rs
  core/sdk/Cargo.toml
  core/sdk/src/api/apps.rs
  core/sdk/src/api/device/device_peristence.rs
  core/sdk/src/api/firebolt/fb_authentication.rs
  core/sdk/src/extn/ffi/ffi_jsonrpsee.rs
  core/sdk/src/extn/ffi/mod.rs
  core/sdk/src/utils/logger.rs
  device/thunder/Cargo.toml
  device/thunder_ripple_sdk/Cargo.toml
  distributor/general/Cargo.toml
  docs/how-to.md
  examples/rpc_extn/Cargo.toml
  systemd/ripple.service
Labels: enhancement

#198 refactor: PermissionHandler::fetch_and_store args as reference
  core/main/src/firebolt/firebolt_ws.rs
  core/main/src/firebolt/handlers/advertising_rpc.rs
  core/main/src/firebolt/handlers/capabilities_rpc.rs
  core/main/src/firebolt/handlers/device_rpc.rs
  core/main/src/firebolt/handlers/voice_guidance_rpc.rs
  core/main/src/processor/account_link_processor.rs
  core/main/src/service/apps/delegated_launcher_handler.rs
  core/main/src/state/cap/permitted_state.rs
  device/thunder_ripple_sdk/src/processors/thunder_device_info.rs
  device/thunder_ripple_sdk/src/processors/thunder_persistent_store.rs
Labels: resiliency, ci-cd

#204 fix: Exit with error code gracefully
  core/main/Cargo.toml
  core/main/src/bootstrap/boot.rs
  core/main/src/main.rs
  core/main/src/service/telemetry_builder.rs
Labels: resiliency

#206 Fixed Extn_Sender arg issue in contract test
  device/thunder_ripple_sdk/src/tests/contracts/contract_utils.rs
Labels: ci-cd
